// <auto-generated />
using System;
using LateralCms.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LateralCms.Infrastructure.Migrations
{
    [DbContext(typeof(LateralCmsContext))]
    partial class LateralCmsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.18");

            modelBuilder.Entity("LateralCms.Domain.Entities.CmsEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LatestVersionId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PublishedVersionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Id", "LatestVersionId")
                        .IsUnique();

                    b.HasIndex("Id", "PublishedVersionId")
                        .IsUnique();

                    b.ToTable("CmsEntity", (string)null);
                });

            modelBuilder.Entity("LateralCms.Domain.Entities.CmsEntityVersion", b =>
                {
                    b.Property<string>("EntityId")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Payload")
                        .HasColumnType("TEXT");

                    b.HasKey("EntityId", "Version");

                    b.ToTable("CmsEntityVersion", (string)null);
                });

            modelBuilder.Entity("LateralCms.Domain.Entities.CmsEntityVisibilityOverride", b =>
                {
                    b.Property<string>("CmsEntityId")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("CmsEntityId");

                    b.ToTable("CmsEntityVisibilityOverride", (string)null);
                });

            modelBuilder.Entity("LateralCms.Domain.Entities.CmsEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Payload")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ProcessEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ProcessStart")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CmsEvent", (string)null);
                });

            modelBuilder.Entity("LateralCms.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasMaxLength(50)
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("LateralCms.Domain.Entities.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("UserRole", (string)null);
                });

            modelBuilder.Entity("LateralCms.Domain.Entities.CmsEntity", b =>
                {
                    b.HasOne("LateralCms.Domain.Entities.CmsEntityVersion", "LatestVersion")
                        .WithOne()
                        .HasForeignKey("LateralCms.Domain.Entities.CmsEntity", "Id", "LatestVersionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("LateralCms.Domain.Entities.CmsEntityVersion", "PublishedVersion")
                        .WithOne()
                        .HasForeignKey("LateralCms.Domain.Entities.CmsEntity", "Id", "PublishedVersionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("LatestVersion");

                    b.Navigation("PublishedVersion");
                });

            modelBuilder.Entity("LateralCms.Domain.Entities.CmsEntityVersion", b =>
                {
                    b.HasOne("LateralCms.Domain.Entities.CmsEntity", "Entity")
                        .WithMany("Versions")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("LateralCms.Domain.Entities.CmsEntityVisibilityOverride", b =>
                {
                    b.HasOne("LateralCms.Domain.Entities.CmsEntity", null)
                        .WithOne()
                        .HasForeignKey("LateralCms.Domain.Entities.CmsEntityVisibilityOverride", "CmsEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LateralCms.Domain.Entities.User", b =>
                {
                    b.HasOne("LateralCms.Domain.Entities.UserRole", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("LateralCms.Domain.Entities.CmsEntity", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("LateralCms.Domain.Entities.UserRole", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
